
/**************************************************************
 *	
 *	GlassAnimals, 8 bit, 11025Hz,
 *	1 channel, 228282 bytes/channel
 *	Total Size: 1 * 228282 + 4 (header) = 228326 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/richavirmani/Documents/Fall2019/cs2261new/finalproject/GlassAnimals.wav
 *	Time-stamp: Sun Nov 24 22:35:11 2019
 *	
 **************************************************************/

#ifndef __GLASSANIMALSH__
#define __GLASSANIMALSH__

#define GLASSANIMALSFREQ 11025
#define GLASSANIMALSLEN 228282

extern const unsigned char GlassAnimals[228282];

#endif /* __GLASSANIMALSH__ */
