
/**************************************************************
 *	
 *	Laser, 8 bit, 11025Hz,
 *	1 channel, 14177 bytes/channel
 *	Total Size: 1 * 14177 + 4 (header) = 14221 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/richavirmani/Documents/Fall2019/cs2261new/finalproject/Laser.wav
 *	Time-stamp: Sun Nov 24 17:15:00 2019
 *	
 **************************************************************/

#ifndef __LASERH__
#define __LASERH__

#define LASERFREQ 11025
#define LASERLEN 14177

extern const unsigned char Laser[14177];

#endif /* __LASERH__ */
