
/**************************************************************
 *	
 *	SpaceSong, 8 bit, 11025Hz,
 *	1 channel, 3534336 bytes/channel
 *	Total Size: 1 * 3534336 + 4 (header) = 3534380 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/richavirmani/Documents/Fall2019/cs2261new/finalproject/SpaceSong.wav
 *	Time-stamp: Sun Nov 24 17:14:16 2019
 *	
 **************************************************************/

#ifndef __SPACESONGH__
#define __SPACESONGH__

#define SPACESONGFREQ 11025
#define SPACESONGLEN 3534336

extern const unsigned char SpaceSong[3534336];

#endif /* __SPACESONGH__ */
